// client-react/src/components/Key.js
import React from "react";
import './Key.css';

class Key extends React.Component {
  render() {
    return (
      <div>
        <form>
          <span className="span-input">
            <input className="input" type="text" value={this.props.message} onChange={(event) => this.props.onChange(event)} />
          </span>
          <span className="span-button">
            <button className="button" onClick={(event) => this.props.onClick(event)}>Send</button>
          </span>
        </form>
      </div>
    );
  }
}

export default Key;

// client-angular/src/app/key/key.component.ts
import { Component } from '@angular/core';
import { IOService } from '../service/io.service';

@Component({
  selector: 'app-key',
  templateUrl: './key.component.html',
  styleUrls: ['./key.component.css']
})
export class KeyComponent {
  message;

  constructor(private ioService: IOService) {
  }

  sendMessage() {
    this.ioService.sendMessage(this.message);
    this.message = '';
  }
}

<form>
  <span class="span-input">
    <input [(ngModel)]="message" [ngModelOptions]="{standalone: true}" class="input" />
  </span>
  <span class="span-button">
    <button (click)="sendMessage()" class="button">Send</button>
  </span>
</form>
