// client/src/app/chat/chat.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ChatService } from './chat.service';

@Component({
  selector: 'app-chat',
  templateUrl: './chat.component.html',
  styleUrls: ['./chat.component.css'],
  providers: [ChatService]
})
export class ChatComponent implements OnInit, OnDestroy {
  messages = [];
  connection;
  message;

  constructor(private chatService: ChatService) { }

  sendMessage() {
    this.chatService.sendMessage(this.message);
    this.message = '';
  }

  ngOnInit() {
    this.connection = this.chatService.getMessages().subscribe(message => {
      this.messages.push(message);
    });
  }

  ngOnDestroy() {
    this.connection.unsubscribe();
  }
}

<div class="main posts-alert"></div>
<div class="scroller posts">
  <article id="messages" *ngFor="let message of messages" class="card post">
    <div class="post-content">
      <img class="post-avatar" alt="" width="40" height="40" src="assets/{{message.avatar}}-1x.jpg">
      <div class="post-text-content">
        <div class="post-title">
          <h1 class="post-heading">{{message.name}}</h1>
          <time class="post-time" [dateTime]="message.time">{{message.timeDifference}}</time>
        </div>
        <p>
          {{message.text}}
        </p>
      </div>
    </div>
  </article>
</div>

<form action="">
  <input [(ngModel)]="message" [ngModelOptions]="{standalone: true}" />
  <button (click)="sendMessage()">Send</button>
</form>

// client-react/src/components/Chat.js
import React from "react";

class Chat extends React.Component {
  render() {
    var _ = this;
    return (
      <div className="scroller posts" id="scrollx">
        {this.props.messages.map(message => {
          return (
            <article className="card post">
              <div className="post-content">
                <img className="post-avatar" alt="" width="40" height="40" src={_.props.images[message.name]} />
                <div className="post-text-content">
                  <div className="post-title">
                    <h1 className="post-heading">{message.name}</h1>
                    <time className="post-time" datetime={message.time}>{message.timeDifference}</time>
                  </div>
                  <p>{message.text}</p>
                </div>
              </div>
            </article>
          )
        })}
      </div>
    );
  }
}

export default Chat;
