// client/src/app/app.component.ts
import { Component } from '@angular/core';
import { IOService } from './service/io.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [IOService]
})
export class AppComponent {
  title = 'swittr';
}

<header class="toolbar">
  <h1 class="site-title">Swittr</h1>
</header>
<main class="main">
  <div class="posts-alert"></div>
  <app-chat class="scroller posts"></app-chat>
</main>
<footer class="footer">
  <app-key></app-key>
</footer>

// client-react/src/App.js
import React, { Component } from 'react';
import './App.css';
import Chat from "./Chat";
import Toast from "./Toast";
import Key from "./Key";

class App extends Component {
  render() {
    return ([
      <header class="toolbar">
        <h1 class="site-title">Swittr</h1>
      </header>,
      <main className="main">
        <div className="posts-alert"></div>
        <Chat />
        <Toast />
      </main>,
      <footer class="footer">
        <Key />
      </footer>
    ]);
  }
}

export default App;
