// client-angular/src/app/key/key.component.ts
import { Component } from '@angular/core';
import { IOService } from '../service/io.service';

@Component({
  selector: 'app-key',
  templateUrl: './key.component.html',
  styleUrls: ['./key.component.css']
})
export class KeyComponent {
  message;

  constructor(private ioService: IOService) {
  }

  sendMessage() {
    this.ioService.sendMessage(this.message);
    this.message = '';
  }
}

<form>
  <span class="span-input">
    <input [(ngModel)]="message" [ngModelOptions]="{standalone: true}" class="input" />
  </span>
  <span class="span-button">
    <button (click)="sendMessage()" class="button">Send</button>
  </span>
</form>

// client-react/src/Key.js
import React from "react";
import './App.css';
import './Key.css';

class Key extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      username: '',
      message: '',
      buttons: []
    };
  }

  render() {
    return (
      <div>
        <form>
          <span class="span-input">
            <input class="input" />
          </span>
          <span class="span-button">
            <button onClick="sendMessage()" class="button">Send</button>
          </span>
        </form>
      </div>
    );
  }
}

export default Key;
